root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "bin/bot"
  include_ext = ["go", "tpl", "tmpl", "html"] 
  exclude_dir = ["vendor", "bin"]
  exclude_file = ["air.toml"]
  follow_symlink = true 
  delay = 1000
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  full_bin = ""
  include_dir = []
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

  # Determine the OS and set build command accordingly
  cmd = """
  {{- if eq .OS "windows" -}}
  go build -o ./bin/bot.exe ./cmd/bot/main.go
  {{- else -}}
  go build -o ./bin/bot ./cmd/bot/main.go
  {{- end -}}
  """

[runner]
  # Determine the OS and set run command accordingly
  cmd = """
  {{- if eq .OS "windows" -}}
  cmd /C bin\\bot.exe
  {{- else -}}
  ./bin/bot
  {{- end -}}
  """

  watch_delay = 1000  # Delay before restarting (in milliseconds)
  watch_dirs = ["./"]  # Directories to watch
  watch_files = ["./cmd/bot/main.go"]  # Files to watch specifically
  restart_on_error = true  # Restart on build error

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
